# Generated by Buildr 1.4.12, change to your liking


# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "sorting-algorithms-in-java"
COPYRIGHT = "Wahid Sadik"
#GOOGLE_GUAVA = "com.google.guava:guava:jar:14.0.1"
JUNIT4 = "junit:junit:jar:4.11"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

desc "The Sorting-algorithms-in-java project"
define "sorting-algorithms-in-java" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  compile.with JUNIT4
  test.compile.with JUNIT4
  package(:jar)
end
